import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#ffffff',
    alignItems: 'center',
  },
  header: {
    backgroundColor: '#00a6ff',
    width: '100%',
    paddingTop: 70,
    paddingBottom: 40,
    paddingHorizontal: 20,
  },
  headerRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  loginButton: {
    backgroundColor: '#ffffff',
    paddingVertical: 8,
    paddingHorizontal: 15,
    borderRadius: 25,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 4,
    elevation: 2,
  },
  loginButtonText: {
    color: '#00a6ff',
    fontSize: 16,
    fontWeight: '600',
  },
  headerRight: {
    paddingRight: 10,
  },
  title: {
    fontSize: 32,
    fontWeight: '700',
    color: '#ffffff',
  },
  avatarWrapper: {
    marginTop: 25,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarCircle: {
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: '#34cfff',
    justifyContent: 'center',
    alignItems: 'center',
  },
  avatarIcon: {
    width: 50,
    height: 50,
    resizeMode: 'contain',
  },
  editIconWrapper: {
    position: 'absolute',
    bottom: 5,
    right: '35%',
    backgroundColor: '#003b78',
    width: 36,
    height: 36,
    borderRadius: 18,
    justifyContent: 'center',
    alignItems: 'center',
  },
  editIcon: {
    width: 22,
    height: 22,
    resizeMode: 'contain',
  },
  headerSpacer: {
    width: '100%',
    height: 70,
    backgroundColor: '#F7FBFF',
  },
  inputRow: {
    width: '85%',
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 30,
    borderBottomWidth: 2,
    borderColor: '#00a6ff',
    paddingBottom: 3,
  },
  inputLeftIcon: {
    width: 20,
    height: 20,
    marginRight: 8,
    resizeMode: 'contain',
  },
  input: {
    flex: 1,
    fontSize: 16,
  },
  rowButtons: {
    width: '85%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 25,
  },
  skipButton: {
    backgroundColor: '#ffffff',
    paddingVertical: 8,
    paddingHorizontal: 20,
    borderRadius: 25,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 4,
    elevation: 2,
  },
  skipButtonText: {
    color: '#00a6ff',
    fontSize: 16,
    fontWeight: '600',
  },
  button: {
    backgroundColor: '#00a6ff',
    width: 60,
    height: 60,
    borderRadius: 35,
    justifyContent: 'center',
    alignItems: 'center',
  },
  disabled: {
    opacity: 0.4,
  },
  buttonIcon: {
    fontSize: 30,
    color: '#ffffff',
  },
});